CC = g++

CFLAGS = -Wall

all: AddTwoNumbers_basic AddTwoNumbers_advance AddTwoNumbers_string AddTwoNumbers_string_2

AddTwoNumbers_basic:
	$(CC) $(CFLAGS) -o AddTwoNumbers_basic AddTwoNumbers_basic.cpp

AddTwoNumbers_advance:
	$(CC) $(CFLAGS) -o AddTwoNumbers_advance AddTwoNumbers_advance.cpp

AddTwoNumbers_string:
	$(CC) $(CFLAGS) -o AddTwoNumbers_string AddTwoNumbers_string.cpp

AddTwoNumbers_string_2:
	$(CC) $(CFLAGS) -o AddTwoNumbers_string_2 AddTwoNumbers_string_2.cpp